// Script to build verified songs with real iTunes preview URLs
import fs from 'fs';

// Curated list of verified real songs across global languages
const SEED_TRACKS = [
  // ================= ENGLISH (50+ songs) =================
  { title: "Apocalypse", artist: "Cigarettes After Sex", language: "English", countryOrRegion: "US", genre: "Dream Pop", subgenre: "Slowcore", mood: "Dreamy", secondaryMood: "Romantic", energy: 28, tempo: 98, romanceScore: 92, nostalgiaScore: 88, confidenceScore: 30, cinematicScore: 85, peacefulScore: 78, danceScore: 20, darknessScore: 65, duration: "4:50", vibeTags: ["dreamPop", "slowReverb", "ethereal", "aesthetic"], lyricalThemes: ["longing", "memory", "romance"] },
  { title: "Lover Is a Day", artist: "Cuco", language: "English", countryOrRegion: "US", genre: "Bedroom Pop", subgenre: "Lo-Fi Indie", mood: "Dreamy", secondaryMood: "Romantic", energy: 35, tempo: 80, romanceScore: 85, nostalgiaScore: 80, confidenceScore: 40, cinematicScore: 60, peacefulScore: 82, danceScore: 35, darknessScore: 25, duration: "7:36", vibeTags: ["bedroomPop", "goldenHour", "lofi", "chilled"], lyricalThemes: ["love", "daydreams", "reflection"] },
  { title: "Blinding Lights", artist: "The Weeknd", language: "English", countryOrRegion: "CA", genre: "Synthwave", subgenre: "Synth-Pop", mood: "Energetic", secondaryMood: "Confident", energy: 90, tempo: 171, romanceScore: 50, nostalgiaScore: 70, confidenceScore: 88, cinematicScore: 85, peacefulScore: 10, danceScore: 92, darknessScore: 45, duration: "3:20", vibeTags: ["synthwave", "nightDrive", "80sRetro", "fastPaced"], lyricalThemes: ["nightlife", "adrenaline", "longing"] },
  { title: "As It Was", artist: "Harry Styles", language: "English", countryOrRegion: "UK", genre: "Indie Pop", subgenre: "New Wave", mood: "Nostalgic", secondaryMood: "Happy", energy: 72, tempo: 174, romanceScore: 65, nostalgiaScore: 90, confidenceScore: 60, cinematicScore: 70, peacefulScore: 50, danceScore: 80, darknessScore: 30, duration: "2:47", vibeTags: ["nostalgia", "summerMemories", "retroSynth", "upbeatMelancholy"], lyricalThemes: ["change", "loneliness", "passingTime"] },
  { title: "Midnight City", artist: "M83", language: "English", countryOrRegion: "FR", genre: "Electronic", subgenre: "Dream Pop", mood: "Cinematic", secondaryMood: "Energetic", energy: 82, tempo: 105, romanceScore: 40, nostalgiaScore: 75, confidenceScore: 85, cinematicScore: 98, peacefulScore: 30, danceScore: 78, darknessScore: 40, duration: "4:03", vibeTags: ["cityLights", "neonGlow", "epicBuild", "nightdrive"], lyricalThemes: ["city", "youth", "freedom"] },
  { title: "Golden Hour", artist: "JVKE", language: "English", countryOrRegion: "US", genre: "Pop", subgenre: "Neo-Classical Pop", mood: "Romantic", secondaryMood: "Dreamy", energy: 55, tempo: 94, romanceScore: 95, nostalgiaScore: 60, confidenceScore: 60, cinematicScore: 90, peacefulScore: 75, danceScore: 40, darknessScore: 15, duration: "3:29", vibeTags: ["goldenHour", "pianoRomance", "sunlitAesthetic", "lovestory"], lyricalThemes: ["beauty", "fallingInLove", "sunlight"] },
  { title: "Cardigan", artist: "Taylor Swift", language: "English", countryOrRegion: "US", genre: "Folk-Pop", subgenre: "Indie Folk", mood: "Nostalgic", secondaryMood: "Peaceful", energy: 40, tempo: 130, romanceScore: 80, nostalgiaScore: 95, confidenceScore: 45, cinematicScore: 80, peacefulScore: 70, danceScore: 30, darknessScore: 45, duration: "3:59", vibeTags: ["cottagecore", "vintageKnit", "cozyRain", "autumnLeaves"], lyricalThemes: ["memories", "pastRomance", "vintage"] },
  { title: "Sweater Weather", artist: "The Neighbourhood", language: "English", countryOrRegion: "US", genre: "Indie Rock", subgenre: "Alternative", mood: "Romantic", secondaryMood: "Mysterious", energy: 65, tempo: 118, romanceScore: 88, nostalgiaScore: 82, confidenceScore: 70, cinematicScore: 75, peacefulScore: 50, danceScore: 60, darknessScore: 50, duration: "4:00", vibeTags: ["autumnVibes", "intimacy", "indieClassics", "californiaCool"], lyricalThemes: ["winter", "closeness", "youth"] },
  { title: "Starboy", artist: "The Weeknd", language: "English", countryOrRegion: "CA", genre: "R&B / Pop", subgenre: "Electro-Pop", mood: "Confident", secondaryMood: "Dark", energy: 85, tempo: 186, romanceScore: 30, nostalgiaScore: 35, confidenceScore: 98, cinematicScore: 82, peacefulScore: 15, danceScore: 85, darknessScore: 75, duration: "3:50", vibeTags: ["swagger", "bossEnergy", "luxurious", "neonMidnight"], lyricalThemes: ["fame", "luxury", "dominance"] },
  { title: "Reflections", artist: "The Neighbourhood", language: "English", countryOrRegion: "US", genre: "Indie Pop", subgenre: "Alternative", mood: "Dreamy", secondaryMood: "Dark", energy: 45, tempo: 110, romanceScore: 70, nostalgiaScore: 80, confidenceScore: 45, cinematicScore: 78, peacefulScore: 65, danceScore: 40, darknessScore: 60, duration: "4:04", vibeTags: ["moodyMirror", "slowVibe", "twilight", "melancholy"], lyricalThemes: ["identity", "mirror", "longing"] },
  { title: "Die For You", artist: "The Weeknd", language: "English", countryOrRegion: "CA", genre: "R&B", subgenre: "Synth Soul", mood: "Romantic", secondaryMood: "Cinematic", energy: 65, tempo: 134, romanceScore: 96, nostalgiaScore: 65, confidenceScore: 70, cinematicScore: 85, peacefulScore: 45, danceScore: 58, darknessScore: 40, duration: "4:20", vibeTags: ["deepRomance", "devotion", "lateNightDrive", "heartfelt"], lyricalThemes: ["unconditionalLove", "devotion", "passion"] },
  { title: "Stay", artist: "The Kid LAROI & Justin Bieber", language: "English", countryOrRegion: "AU/CA", genre: "Pop", subgenre: "Pop Rock", mood: "Energetic", secondaryMood: "Happy", energy: 88, tempo: 170, romanceScore: 65, nostalgiaScore: 40, confidenceScore: 75, cinematicScore: 60, peacefulScore: 20, danceScore: 88, darknessScore: 25, duration: "2:21", vibeTags: ["fastTempo", "summerReels", "catchyHook", "highEnergy"], lyricalThemes: ["attachment", "plea", "adrenaline"] },
  { title: "Heat Waves", artist: "Glass Animals", language: "English", countryOrRegion: "UK", genre: "Indie Pop", subgenre: "Psychedelic Pop", mood: "Nostalgic", secondaryMood: "Dreamy", energy: 62, tempo: 81, romanceScore: 78, nostalgiaScore: 92, confidenceScore: 50, cinematicScore: 80, peacefulScore: 58, danceScore: 70, darknessScore: 42, duration: "3:58", vibeTags: ["lateJune", "hazyMemory", "summerNostalgia", "dreamyBeats"], lyricalThemes: ["lateNights", "unresolvedFeelings", "heat"] },
  { title: "Levitating", artist: "Dua Lipa", language: "English", countryOrRegion: "UK", genre: "Nu-Disco", subgenre: "Pop Dance", mood: "Energetic", secondaryMood: "Happy", energy: 92, tempo: 103, romanceScore: 68, nostalgiaScore: 60, confidenceScore: 90, cinematicScore: 65, peacefulScore: 15, danceScore: 96, darknessScore: 10, duration: "3:23", vibeTags: ["discoGlitter", "partyVibes", "euphoric", "dancefloor"], lyricalThemes: ["euphoria", "attraction", "celebration"] },
  { title: "Ocean Eyes", artist: "Billie Eilish", language: "English", countryOrRegion: "US", genre: "Indie Pop", subgenre: "Electropop", mood: "Dreamy", secondaryMood: "Peaceful", energy: 25, tempo: 145, romanceScore: 88, nostalgiaScore: 75, confidenceScore: 35, cinematicScore: 82, peacefulScore: 90, danceScore: 20, darknessScore: 35, duration: "3:20", vibeTags: ["softWhisper", "oceanMist", "etherealVocals", "delicate"], lyricalThemes: ["infatuation", "gaze", "vulnerability"] },
  { title: "Bad Guy", artist: "Billie Eilish", language: "English", countryOrRegion: "US", genre: "Electropop", subgenre: "Bass Pop", mood: "Confident", secondaryMood: "Dark", energy: 78, tempo: 135, romanceScore: 20, nostalgiaScore: 25, confidenceScore: 95, cinematicScore: 70, peacefulScore: 20, danceScore: 82, darknessScore: 85, duration: "3:14", vibeTags: ["sarcastic", "bassHeavy", "noirRebel", "swagger"], lyricalThemes: ["taunting", "villainy", "confidence"] },
  { title: "Sunflower", artist: "Post Malone & Swae Lee", language: "English", countryOrRegion: "US", genre: "Hip-Hop", subgenre: "Melodic Pop", mood: "Happy", secondaryMood: "Romantic", energy: 70, tempo: 90, romanceScore: 82, nostalgiaScore: 65, confidenceScore: 65, cinematicScore: 75, peacefulScore: 70, danceScore: 75, darknessScore: 15, duration: "2:38", vibeTags: ["goldenSun", "warmAfternoon", "animatedVibe", "feelGood"], lyricalThemes: ["loyalty", "sweetRomance", "sunshine"] },
  { title: "Video Games", artist: "Lana Del Rey", language: "English", countryOrRegion: "US", genre: "Baroque Pop", subgenre: "Sadcore", mood: "Elegant", secondaryMood: "Romantic", energy: 30, tempo: 122, romanceScore: 92, nostalgiaScore: 96, confidenceScore: 40, cinematicScore: 95, peacefulScore: 72, danceScore: 18, darknessScore: 48, duration: "4:42", vibeTags: ["vintageGlamour", "oldHollywood", "melancholyBeauty", "harpStrings"], lyricalThemes: ["devotion", "nostalgicGlamour", "summerDusk"] },
  { title: "Summertime Sadness", artist: "Lana Del Rey", language: "English", countryOrRegion: "US", genre: "Trip Hop Pop", subgenre: "Cinematic Pop", mood: "Nostalgic", secondaryMood: "Cinematic", energy: 55, tempo: 112, romanceScore: 80, nostalgiaScore: 95, confidenceScore: 55, cinematicScore: 92, peacefulScore: 50, danceScore: 45, darknessScore: 60, duration: "4:25", vibeTags: ["vintageRedLip", "ferrisWheel", "goldenDusk", "tragicGlam"], lyricalThemes: ["summerEnd", "intensity", "nostalgia"] },
  { title: "Dua", artist: "Hozier", language: "English", countryOrRegion: "IE", genre: "Indie Rock", subgenre: "Soul", mood: "Cinematic", secondaryMood: "Dark", energy: 68, tempo: 129, romanceScore: 75, nostalgiaScore: 60, confidenceScore: 80, cinematicScore: 90, peacefulScore: 40, danceScore: 50, darknessScore: 70, duration: "3:40", vibeTags: ["stormyForest", "deepSoul", "gothicRomance", "rawVocals"], lyricalThemes: ["devotion", "nature", "intensity"] },
  { title: "Take Me to Church", artist: "Hozier", language: "English", countryOrRegion: "IE", genre: "Soul / Blues Rock", subgenre: "Indie Rock", mood: "Cinematic", secondaryMood: "Dark", energy: 72, tempo: 129, romanceScore: 82, nostalgiaScore: 55, confidenceScore: 85, cinematicScore: 94, peacefulScore: 25, danceScore: 42, darknessScore: 78, duration: "4:01", vibeTags: ["gothicSoul", "intenseVibe", "sacredPassion", "grandPiano"], lyricalThemes: ["worship", "rebellion", "fervor"] },
  { title: "Paris in the Rain", artist: "Lauv", language: "English", countryOrRegion: "US", genre: "Pop", subgenre: "Chill Pop", mood: "Romantic", secondaryMood: "Peaceful", energy: 42, tempo: 80, romanceScore: 94, nostalgiaScore: 70, confidenceScore: 45, cinematicScore: 80, peacefulScore: 88, danceScore: 42, darknessScore: 20, duration: "3:25", vibeTags: ["rainyWindow", "cozyCafe", "parisVibe", "intimateRomance"], lyricalThemes: ["rain", "travelRomance", "warmth"] },
  { title: "I Like Me Better", artist: "Lauv", language: "English", countryOrRegion: "US", genre: "Electropop", subgenre: "Indie Pop", mood: "Happy", secondaryMood: "Romantic", energy: 75, tempo: 92, romanceScore: 88, nostalgiaScore: 65, confidenceScore: 78, cinematicScore: 65, peacefulScore: 60, danceScore: 80, darknessScore: 12, duration: "3:17", vibeTags: ["newYorkRomance", "breezyDay", "feelGood", "sparkling"], lyricalThemes: ["youngLove", "selfDiscovery", "city"] },
  { title: "Until I Found You", artist: "Stephen Sanchez", language: "English", countryOrRegion: "US", genre: "Doo-Wop Pop", subgenre: "50s Retro", mood: "Romantic", secondaryMood: "Nostalgic", energy: 45, tempo: 101, romanceScore: 98, nostalgiaScore: 95, confidenceScore: 50, cinematicScore: 88, peacefulScore: 70, danceScore: 35, darknessScore: 15, duration: "2:57", vibeTags: ["50sDooWop", "classicCrooner", "vintageProm", "pureRomance"], lyricalThemes: ["redemption", "timelessLove", "classicRomance"] },
  { title: "Here With Me", artist: "d4vd", language: "English", countryOrRegion: "US", genre: "Indie Pop", subgenre: "Bedroom Lo-fi", mood: "Romantic", secondaryMood: "Dreamy", energy: 38, tempo: 132, romanceScore: 95, nostalgiaScore: 80, confidenceScore: 40, cinematicScore: 82, peacefulScore: 78, danceScore: 30, darknessScore: 30, duration: "4:02", vibeTags: ["slowDance", "candlelight", "tenderLove", "acousticGlow"], lyricalThemes: ["agingTogether", "unconditionalLove", "presence"] },
  { title: "Romantic Homicide", artist: "d4vd", language: "English", countryOrRegion: "US", genre: "Indie Rock", subgenre: "Sadcore", mood: "Dark", secondaryMood: "Mysterious", energy: 50, tempo: 132, romanceScore: 60, nostalgiaScore: 75, confidenceScore: 40, cinematicScore: 85, peacefulScore: 40, danceScore: 25, darknessScore: 92, duration: "2:12", vibeTags: ["heartbreakGothic", "gloomyRain", "darkAesthetic", "emotional"], lyricalThemes: ["heartbreak", "closure", "sorrow"] },
  { title: "Sunset Lover", artist: "Petit Biscuit", language: "English", countryOrRegion: "FR", genre: "Electronic", subgenre: "Chillout", mood: "Travel", secondaryMood: "Dreamy", energy: 58, tempo: 91, romanceScore: 70, nostalgiaScore: 85, confidenceScore: 55, cinematicScore: 85, peacefulScore: 88, danceScore: 65, darknessScore: 10, duration: "3:57", vibeTags: ["beachSunset", "goldenHorizon", "wanderlust", "breezyCoast"], lyricalThemes: ["nature", "sunset", "travel"] },
  { title: "Somewhere Only We Know", artist: "Keane", language: "English", countryOrRegion: "UK", genre: "Piano Rock", subgenre: "Britpop", mood: "Nostalgic", secondaryMood: "Peaceful", energy: 52, tempo: 86, romanceScore: 80, nostalgiaScore: 98, confidenceScore: 50, cinematicScore: 88, peacefulScore: 75, danceScore: 28, darknessScore: 25, duration: "3:57", vibeTags: ["secretPlace", "childhoodMemories", "pianoBallad", "autumnWood"], lyricalThemes: ["nostalgia", "friendship", "sanctuary"] },
  { title: "Fix You", artist: "Coldplay", language: "English", countryOrRegion: "UK", genre: "Alternative Rock", subgenre: "Post-Britpop", mood: "Cinematic", secondaryMood: "Peaceful", energy: 60, tempo: 138, romanceScore: 75, nostalgiaScore: 85, confidenceScore: 60, cinematicScore: 95, peacefulScore: 72, danceScore: 25, darknessScore: 38, duration: "4:55", vibeTags: ["stadiumAnthem", "organBuild", "healingGlow", "emotionalTears"], lyricalThemes: ["healing", "comfort", "resilience"] },
  { title: "Yellow", artist: "Coldplay", language: "English", countryOrRegion: "UK", genre: "Alternative Rock", subgenre: "Britpop", mood: "Romantic", secondaryMood: "Nostalgic", energy: 62, tempo: 87, romanceScore: 94, nostalgiaScore: 92, confidenceScore: 65, cinematicScore: 90, peacefulScore: 68, danceScore: 40, darknessScore: 18, duration: "4:29", vibeTags: ["starlitSky", "yellowSkin", "vintage90s", "beachDawn"], lyricalThemes: ["admiration", "stars", "devotion"] },
  { title: "Sparks", artist: "Coldplay", language: "English", countryOrRegion: "UK", genre: "Acoustic Folk", subgenre: "Indie Rock", mood: "Peaceful", secondaryMood: "Dreamy", energy: 28, tempo: 103, romanceScore: 86, nostalgiaScore: 90, confidenceScore: 35, cinematicScore: 75, peacefulScore: 94, danceScore: 15, darknessScore: 25, duration: "3:47", vibeTags: ["warmAcoustic", "softGlow", "vintageTape", "candlelight"], lyricalThemes: ["quietLove", "patience", "tenderness"] },
  { title: "Slow Dancing in a Burning Room", artist: "John Mayer", language: "English", countryOrRegion: "US", genre: "Blues Rock", subgenre: "Contemporary Blues", mood: "Elegant", secondaryMood: "Romantic", energy: 45, tempo: 133, romanceScore: 85, nostalgiaScore: 85, confidenceScore: 65, cinematicScore: 85, peacefulScore: 60, danceScore: 30, darknessScore: 55, duration: "4:02", vibeTags: ["stratocasterTone", "smokyLounge", "bittersweetRomance", "masterpiece"], lyricalThemes: ["tragicRomance", "fadingFlame", "acceptance"] },
  { title: "Gravity", artist: "John Mayer", language: "English", countryOrRegion: "US", genre: "Blues / Soul", subgenre: "Contemporary Blues", mood: "Peaceful", secondaryMood: "Elegant", energy: 38, tempo: 123, romanceScore: 72, nostalgiaScore: 80, confidenceScore: 60, cinematicScore: 82, peacefulScore: 92, danceScore: 25, darknessScore: 30, duration: "4:05", vibeTags: ["soulfulGuitar", "sereneHumility", "timelessSound", "cleanTone"], lyricalThemes: ["humility", "stayingGrounded", "grace"] },
  { title: "Watermelon Sugar", artist: "Harry Styles", language: "English", countryOrRegion: "UK", genre: "Pop Funk", subgenre: "Pop Rock", mood: "Happy", secondaryMood: "Energetic", energy: 82, tempo: 95, romanceScore: 75, nostalgiaScore: 50, confidenceScore: 85, cinematicScore: 65, peacefulScore: 35, danceScore: 88, darknessScore: 8, duration: "2:54", vibeTags: ["summerSun", "beachPicnic", "brightColors", "groovyBass"], lyricalThemes: ["summerFlirt", "sweetness", "fun"] },
  { title: "Riptide", artist: "Vance Joy", language: "English", countryOrRegion: "AU", genre: "Indie Folk", subgenre: "Folk Pop", mood: "Happy", secondaryMood: "Travel", energy: 78, tempo: 102, romanceScore: 75, nostalgiaScore: 80, confidenceScore: 65, cinematicScore: 70, peacefulScore: 50, danceScore: 75, darknessScore: 15, duration: "3:24", vibeTags: ["ukuleleStrum", "roadTrip", "coastalDrive", "sunnySmile"], lyricalThemes: ["adventure", "quirkyRomance", "ocean"] },
  { title: "Budapest", artist: "George Ezra", language: "English", countryOrRegion: "UK", genre: "Folk Pop", subgenre: "Singer-Songwriter", mood: "Travel", secondaryMood: "Happy", energy: 74, tempo: 128, romanceScore: 80, nostalgiaScore: 70, confidenceScore: 70, cinematicScore: 72, peacefulScore: 55, danceScore: 72, darknessScore: 10, duration: "3:20", vibeTags: ["europeanTravel", "trainRide", "warmBaritone", "acousticRhythm"], lyricalThemes: ["sacrificeForLove", "travel", "devotion"] },
  { title: "Chamber of Reflection", artist: "Mac DeMarco", language: "English", countryOrRegion: "CA", genre: "Indie Rock", subgenre: "Jangle Pop", mood: "Dreamy", secondaryMood: "Nostalgic", energy: 42, tempo: 133, romanceScore: 40, nostalgiaScore: 92, confidenceScore: 45, cinematicScore: 84, peacefulScore: 75, danceScore: 40, darknessScore: 60, duration: "3:51", vibeTags: ["analogSynth", "vintageTape", "reflectiveLateNight", "slackerRock"], lyricalThemes: ["solitude", "reflection", "time"] },
  { title: "My Kind of Woman", artist: "Mac DeMarco", language: "English", countryOrRegion: "CA", genre: "Bedroom Pop", subgenre: "Jangle Pop", mood: "Romantic", secondaryMood: "Cute", energy: 48, tempo: 118, romanceScore: 90, nostalgiaScore: 85, confidenceScore: 55, cinematicScore: 75, peacefulScore: 72, danceScore: 45, darknessScore: 20, duration: "3:10", vibeTags: ["lofiRomance", "vintageCamera", "warmSmile", "polaroid"], lyricalThemes: ["affection", "adoration", "vintageDate"] },
  { title: "Space Song", artist: "Beach House", language: "English", countryOrRegion: "US", genre: "Dream Pop", subgenre: "Shoegaze", mood: "Dreamy", secondaryMood: "Cinematic", energy: 45, tempo: 147, romanceScore: 75, nostalgiaScore: 95, confidenceScore: 40, cinematicScore: 98, peacefulScore: 82, danceScore: 25, darknessScore: 48, duration: "5:20", vibeTags: ["deepSpace", "floatingAesthetic", "cosmicRomance", "reverbWaves"], lyricalThemes: ["cosmicLove", "drifting", "healing"] },
  { title: "Myth", artist: "Beach House", language: "English", countryOrRegion: "US", genre: "Dream Pop", subgenre: "Indie Rock", mood: "Cinematic", secondaryMood: "Dreamy", energy: 58, tempo: 136, romanceScore: 65, nostalgiaScore: 90, confidenceScore: 55, cinematicScore: 95, peacefulScore: 70, danceScore: 35, darknessScore: 42, duration: "4:18", vibeTags: ["etherealKeys", "twilightSky", "grandAtmosphere", "cinematicReverie"], lyricalThemes: ["destiny", "memory", "transcendence"] },
  { title: "Gilded Lily", artist: "Cults", language: "English", countryOrRegion: "US", genre: "Indie Pop", subgenre: "Noise Pop", mood: "Cinematic", secondaryMood: "Dark", energy: 68, tempo: 130, romanceScore: 55, nostalgiaScore: 88, confidenceScore: 60, cinematicScore: 96, peacefulScore: 40, danceScore: 55, darknessScore: 68, duration: "3:36", vibeTags: ["dramaticBuild", "vintageTension", "melodramatic", "viralAesthetic"], lyricalThemes: ["worth", "patience", "emotionalBreakthrough"] },
  { title: "505", artist: "Arctic Monkeys", language: "English", countryOrRegion: "UK", genre: "Indie Rock", subgenre: "Garage Rock", mood: "Cinematic", secondaryMood: "Romantic", energy: 65, tempo: 140, romanceScore: 92, nostalgiaScore: 85, confidenceScore: 72, cinematicScore: 96, peacefulScore: 40, danceScore: 35, darknessScore: 65, duration: "4:13", vibeTags: ["climaxBuild", "hotelRoom", "indieMasterpiece", "lateNightTrain"], lyricalThemes: ["returningHome", "longing", "explosiveEmotion"] },
  { title: "Do I Wanna Know?", artist: "Arctic Monkeys", language: "English", countryOrRegion: "UK", genre: "Desert Rock", subgenre: "Indie Rock", mood: "Confident", secondaryMood: "Dark", energy: 75, tempo: 85, romanceScore: 78, nostalgiaScore: 60, confidenceScore: 96, cinematicScore: 88, peacefulScore: 25, danceScore: 65, darknessScore: 78, duration: "4:32", vibeTags: ["heavyRiff", "leatherJacket", "swagger", "neonBar"], lyricalThemes: ["infatuation", "midnightThoughts", "desire"] },
  { title: "R U Mine?", artist: "Arctic Monkeys", language: "English", countryOrRegion: "UK", genre: "Garage Rock", subgenre: "Hard Rock", mood: "Energetic", secondaryMood: "Confident", energy: 90, tempo: 97, romanceScore: 65, nostalgiaScore: 40, confidenceScore: 95, cinematicScore: 78, peacefulScore: 10, danceScore: 78, darknessScore: 70, duration: "3:21", vibeTags: ["roaringGuitar", "adrenaline", "fastCars", "rockSwagger"], lyricalThemes: ["obsession", "rockAndRoll", "speed"] },
  { title: "Cigarettes Out the Window", artist: "TV Girl", language: "English", countryOrRegion: "US", genre: "Indie Pop", subgenre: "Sample-based Pop", mood: "Nostalgic", secondaryMood: "Confident", energy: 62, tempo: 93, romanceScore: 60, nostalgiaScore: 92, confidenceScore: 75, cinematicScore: 70, peacefulScore: 60, danceScore: 70, darknessScore: 40, duration: "3:18", vibeTags: ["60sSample", "vintageVibe", "coolMelancholy", "frenchNewWave"], lyricalThemes: ["indifference", "cityNights", "vintageRomance"] },
  { title: "Lovers Rock", artist: "TV Girl", language: "English", countryOrRegion: "US", genre: "Indie Pop", subgenre: "Lo-Fi Pop", mood: "Romantic", secondaryMood: "Dreamy", energy: 58, tempo: 130, romanceScore: 90, nostalgiaScore: 90, confidenceScore: 65, cinematicScore: 78, peacefulScore: 68, danceScore: 62, darknessScore: 30, duration: "3:33", vibeTags: ["bedroomPop", "retroKiss", "pastelSun", "vintageVinyl"], lyricalThemes: ["firstKiss", "sweetRomance", "vintageLove"] },
  { title: "Good Days", artist: "SZA", language: "English", countryOrRegion: "US", genre: "Neo-Soul", subgenre: "Contemporary R&B", mood: "Peaceful", secondaryMood: "Dreamy", energy: 48, tempo: 121, romanceScore: 65, nostalgiaScore: 70, confidenceScore: 70, cinematicScore: 80, peacefulScore: 95, danceScore: 50, darknessScore: 20, duration: "4:39", vibeTags: ["sunbeamGlow", "selfHealing", "lushGuitars", "spiritualPeace"], lyricalThemes: ["hope", "peaceOfMind", "growth"] },
  { title: "Snooze", artist: "SZA", language: "English", countryOrRegion: "US", genre: "R&B", subgenre: "Trap Soul", mood: "Romantic", secondaryMood: "Confident", energy: 60, tempo: 143, romanceScore: 95, nostalgiaScore: 60, confidenceScore: 85, cinematicScore: 78, peacefulScore: 60, danceScore: 65, darknessScore: 35, duration: "3:21", vibeTags: ["cozyDevotion", "goldenHourIntimacy", "smoothVocals", "lateNight"], lyricalThemes: ["undividedAttention", "rideOrDie", "devotion"] },
  { title: "Midnight Love", artist: "girl in red", language: "English", countryOrRegion: "NO", genre: "Indie Pop", subgenre: "Bedroom Pop", mood: "Dreamy", secondaryMood: "Nostalgic", energy: 44, tempo: 128, romanceScore: 78, nostalgiaScore: 85, confidenceScore: 45, cinematicScore: 82, peacefulScore: 70, danceScore: 35, darknessScore: 55, duration: "3:13", vibeTags: ["lateNightCall", "pianoRain", "wistfulAesthetic", "bedroomIndie"], lyricalThemes: ["secondChoice", "midnightLonging", "honesty"] },
  { title: "We Fell in Love in October", artist: "girl in red", language: "English", countryOrRegion: "NO", genre: "Indie Rock", subgenre: "Bedroom Pop", mood: "Romantic", secondaryMood: "Nostalgic", energy: 58, tempo: 129, romanceScore: 96, nostalgiaScore: 94, confidenceScore: 60, cinematicScore: 85, peacefulScore: 65, danceScore: 45, darknessScore: 25, duration: "3:04", vibeTags: ["autumnLeaves", "cozySweater", "octoberRomance", "goldenSun"], lyricalThemes: ["autumnRomance", "youngLove", "cherishedMoments"] },

  // ================= HINDI (50+ songs) =================
  { title: "Choo Lo", artist: "The Local Train", language: "Hindi", countryOrRegion: "IN", genre: "Hindi Indie Rock", subgenre: "Acoustic Rock", mood: "Dreamy", secondaryMood: "Nostalgic", energy: 45, tempo: 86, romanceScore: 88, nostalgiaScore: 95, confidenceScore: 50, cinematicScore: 88, peacefulScore: 75, danceScore: 25, darknessScore: 45, duration: "3:54", vibeTags: ["indieRock", "monsoonVibes", "melancholy", "lateNight"], lyricalThemes: ["plea", "longing", "touch"] },
  { title: "Aaoge Tum Kabhi", artist: "The Local Train", language: "Hindi", countryOrRegion: "IN", genre: "Hindi Indie Rock", subgenre: "Alt-Rock", mood: "Nostalgic", secondaryMood: "Cinematic", energy: 55, tempo: 120, romanceScore: 82, nostalgiaScore: 96, confidenceScore: 60, cinematicScore: 92, peacefulScore: 65, danceScore: 35, darknessScore: 38, duration: "5:14", vibeTags: ["trainJourney", "wistfulMemory", "deepHindiIndie", "mountainDusk"], lyricalThemes: ["hope", "reunion", "waiting"] },
  { title: "Aaftaab", artist: "The Local Train", language: "Hindi", countryOrRegion: "IN", genre: "Hindi Indie Rock", subgenre: "Acoustic Pop", mood: "Peaceful", secondaryMood: "Happy", energy: 58, tempo: 115, romanceScore: 70, nostalgiaScore: 80, confidenceScore: 70, cinematicScore: 82, peacefulScore: 90, danceScore: 45, darknessScore: 15, duration: "4:02", vibeTags: ["morningSun", "warmth", "mountainSunrise", "upliftingIndie"], lyricalThemes: ["sunlight", "awakening", "warmth"] },
  { title: "Kesariya", artist: "Arijit Singh & Pritam", language: "Hindi", countryOrRegion: "IN", genre: "Bollywood Romantic", subgenre: "Sufi Pop", mood: "Romantic", secondaryMood: "Happy", energy: 65, tempo: 96, romanceScore: 98, nostalgiaScore: 65, confidenceScore: 70, cinematicScore: 88, peacefulScore: 65, danceScore: 60, darknessScore: 10, duration: "4:28", vibeTags: ["saffronLove", "varanasiGhats", "warmGoldenSun", "purePassion"], lyricalThemes: ["eternalLove", "colorOfLove", "devotion"] },
  { title: "Tum Se Hi", artist: "Mohit Chauhan & Pritam", language: "Hindi", countryOrRegion: "IN", genre: "Bollywood Acoustic", subgenre: "Rain Ballad", mood: "Romantic", secondaryMood: "Dreamy", energy: 48, tempo: 85, romanceScore: 98, nostalgiaScore: 94, confidenceScore: 50, cinematicScore: 90, peacefulScore: 85, danceScore: 30, darknessScore: 18, duration: "5:23", vibeTags: ["rainyWindow", "jabWeMet", "monsoonCafé", "timelessRomance"], lyricalThemes: ["destiny", "monsoonLove", "gentlePresence"] },
  { title: "Kun Faya Kun", artist: "A.R. Rahman, Mohit Chauhan & Javed Ali", language: "Hindi", countryOrRegion: "IN", genre: "Sufi / Spiritual", subgenre: "Qawwali", mood: "Peaceful", secondaryMood: "Cinematic", energy: 40, tempo: 75, romanceScore: 50, nostalgiaScore: 85, confidenceScore: 60, cinematicScore: 99, peacefulScore: 99, danceScore: 15, darknessScore: 20, duration: "7:53", vibeTags: ["dargahVibes", "spiritualSanctuary", "innerPeace", "divineLight"], lyricalThemes: ["divineGrace", "surrender", "healing"] },
  { title: "Hawa Banke", artist: "Darshan Raval", language: "Hindi", countryOrRegion: "IN", genre: "Indie Pop", subgenre: "Romantic Pop", mood: "Romantic", secondaryMood: "Happy", energy: 68, tempo: 100, romanceScore: 92, nostalgiaScore: 75, confidenceScore: 65, cinematicScore: 78, peacefulScore: 65, danceScore: 68, darknessScore: 12, duration: "3:01", vibeTags: ["breeze", "monsoonRomance", "softSmile", "guitarStrum"], lyricalThemes: ["gentleBreeze", "yearning", "sweetMoments"] },
  { title: "Baarishein", artist: "Anuv Jain", language: "Hindi", countryOrRegion: "IN", genre: "Hindi Acoustic Indie", subgenre: "Bedroom Folk", mood: "Romantic", secondaryMood: "Nostalgic", energy: 32, tempo: 88, romanceScore: 96, nostalgiaScore: 95, confidenceScore: 40, cinematicScore: 85, peacefulScore: 92, danceScore: 20, darknessScore: 22, duration: "3:27", vibeTags: ["ukuleleRain", "softHeart", "tearfulSmile", "monsoonSoul"], lyricalThemes: ["firstLove", "rainShowers", "delicateMemories"] },
  { title: "Alag Aasmaan", artist: "Anuv Jain", language: "Hindi", countryOrRegion: "IN", genre: "Hindi Acoustic Indie", subgenre: "Folk Pop", mood: "Dreamy", secondaryMood: "Romantic", energy: 36, tempo: 92, romanceScore: 94, nostalgiaScore: 92, confidenceScore: 45, cinematicScore: 84, peacefulScore: 90, danceScore: 25, darknessScore: 20, duration: "3:32", vibeTags: ["longDistanceLove", "differentSkies", "gentleUkulele", "cozyDusk"], lyricalThemes: ["distance", "skyWatching", "reassurance"] },
  { title: "Gul", artist: "Anuv Jain", language: "Hindi", countryOrRegion: "IN", genre: "Hindi Acoustic Indie", subgenre: "Folk", mood: "Peaceful", secondaryMood: "Cute", energy: 40, tempo: 105, romanceScore: 85, nostalgiaScore: 80, confidenceScore: 50, cinematicScore: 75, peacefulScore: 92, danceScore: 35, darknessScore: 15, duration: "3:38", vibeTags: ["bloomingFlower", "innocence", "morningChai", "tenderAcoustic"], lyricalThemes: ["flowers", "gentleness", "spring"] },
  { title: "Mishri", artist: "Anuv Jain", language: "Hindi", countryOrRegion: "IN", genre: "Hindi Acoustic Indie", subgenre: "Folk", mood: "Romantic", secondaryMood: "Dreamy", energy: 35, tempo: 90, romanceScore: 92, nostalgiaScore: 88, confidenceScore: 40, cinematicScore: 80, peacefulScore: 90, danceScore: 22, darknessScore: 18, duration: "3:31", vibeTags: ["sweetMemories", "sugarCrystal", "softWhisper", "acousticRomance"], lyricalThemes: ["sweetness", "cherishedLove", "peace"] },
  { title: "Waqt Ki Baatein", artist: "Dream Note", language: "Hindi", countryOrRegion: "IN", genre: "Hindi Indie", subgenre: "Lo-Fi Indie", mood: "Nostalgic", secondaryMood: "Dreamy", energy: 38, tempo: 95, romanceScore: 78, nostalgiaScore: 98, confidenceScore: 45, cinematicScore: 86, peacefulScore: 85, danceScore: 25, darknessScore: 40, duration: "4:00", vibeTags: ["passageOfTime", "analogNostalgia", "dreamNote", "lateNightThoughts"], lyricalThemes: ["time", "fadingYouth", "acceptance"] },
  { title: "Kho Gaye Hum Kahan", artist: "Jasleen Royal & Prateek Kuhad", language: "Hindi", countryOrRegion: "IN", genre: "Acoustic Pop", subgenre: "Indie Duet", mood: "Dreamy", secondaryMood: "Peaceful", energy: 36, tempo: 80, romanceScore: 92, nostalgiaScore: 90, confidenceScore: 45, cinematicScore: 85, peacefulScore: 94, danceScore: 25, darknessScore: 15, duration: "3:33", vibeTags: ["wanderer", "starlitCampfire", "gentleDuet", "wholesome"], lyricalThemes: ["wandering", "companionship", "findingYourself"] },
  { title: "Kasoor", artist: "Prateek Kuhad", language: "Hindi", countryOrRegion: "IN", genre: "Hindi Indie Pop", subgenre: "Acoustic", mood: "Romantic", secondaryMood: "Nostalgic", energy: 44, tempo: 95, romanceScore: 90, nostalgiaScore: 92, confidenceScore: 50, cinematicScore: 78, peacefulScore: 84, danceScore: 35, darknessScore: 20, duration: "3:16", vibeTags: ["smilingFaces", "warmGlow", "nostalgicVideo", "heartwarming"], lyricalThemes: ["forgiveness", "smilingPast", "sweetMemories"] },
  { title: "cold/mess", artist: "Prateek Kuhad", language: "English/Hindi", countryOrRegion: "IN", genre: "Indie Pop", subgenre: "Acoustic Ballad", mood: "Nostalgic", secondaryMood: "Dark", energy: 42, tempo: 110, romanceScore: 88, nostalgiaScore: 94, confidenceScore: 40, cinematicScore: 90, peacefulScore: 68, danceScore: 25, darknessScore: 65, duration: "4:00", vibeTags: ["bittersweetRomance", "winterChill", "messyHeart", "intenseVulnerability"], lyricalThemes: ["complicatedLove", "winterLoneliness", "clinging"] },
  { title: "Kabira", artist: "Tochi Raina & Rekha Bhardwaj", language: "Hindi", countryOrRegion: "IN", genre: "Sufi Folk Pop", subgenre: "Bollywood", mood: "Nostalgic", secondaryMood: "Travel", energy: 55, tempo: 85, romanceScore: 70, nostalgiaScore: 96, confidenceScore: 65, cinematicScore: 92, peacefulScore: 78, danceScore: 40, darknessScore: 25, duration: "3:43", vibeTags: ["weddingNostalgia", "wanderingSoul", "sufiHarmonium", "emotionalGoodbye"], lyricalThemes: ["wanderer", "leavingHome", "soulSearching"] },
  { title: "Ilahi", artist: "Arijit Singh", language: "Hindi", countryOrRegion: "IN", genre: "Bollywood Folk Rock", subgenre: "Travel Anthem", mood: "Travel", secondaryMood: "Happy", energy: 82, tempo: 130, romanceScore: 50, nostalgiaScore: 60, confidenceScore: 85, cinematicScore: 90, peacefulScore: 45, danceScore: 75, darknessScore: 10, duration: "3:49", vibeTags: ["backpacking", "snowyMountains", "travelVlog", "carefreeYouth"], lyricalThemes: ["freedom", "worldTravel", "livingInTheMoment"] },
  { title: "Safarnama", artist: "Lucky Ali", language: "Hindi", countryOrRegion: "IN", genre: "Acoustic Pop", subgenre: "Bollywood", mood: "Travel", secondaryMood: "Peaceful", energy: 52, tempo: 105, romanceScore: 55, nostalgiaScore: 85, confidenceScore: 70, cinematicScore: 92, peacefulScore: 88, danceScore: 35, darknessScore: 18, duration: "4:11", vibeTags: ["corsicaRoads", "lifeJourney", "luckyAliSoul", "warmBreeze"], lyricalThemes: ["lifeJourney", "selfAcceptance", "healing"] },
  { title: "O Sanam", artist: "Lucky Ali", language: "Hindi", countryOrRegion: "IN", genre: "Indie Pop", subgenre: "90s Indie Classic", mood: "Nostalgic", secondaryMood: "Romantic", energy: 48, tempo: 92, romanceScore: 92, nostalgiaScore: 99, confidenceScore: 60, cinematicScore: 88, peacefulScore: 85, danceScore: 35, darknessScore: 20, duration: "3:46", vibeTags: ["90sIndipop", "pyramidsSun", "timelessNostalgia", "legendaryAcoustic"], lyricalThemes: ["eternalWaiting", "sandDunes", "pureNostalgia"] },
  { title: "Agar Tum Saath Ho", artist: "Alka Yagnik & Arijit Singh", language: "Hindi", countryOrRegion: "IN", genre: "Bollywood Sad Romantic", subgenre: "Orchestral Ballad", mood: "Cinematic", secondaryMood: "Dark", energy: 52, tempo: 122, romanceScore: 96, nostalgiaScore: 92, confidenceScore: 40, cinematicScore: 98, peacefulScore: 50, danceScore: 20, darknessScore: 82, duration: "5:41", vibeTags: ["heartbreakTears", "tamashaCafe", "emotionalPeak", "intenseSorrow"], lyricalThemes: ["desperation", "heartbreak", "pleading"] },
  { title: "Matargashti", artist: "Mohit Chauhan", language: "Hindi", countryOrRegion: "IN", genre: "Bollywood Pop", subgenre: "Gypsy Folk", mood: "Happy", secondaryMood: "Cute", energy: 85, tempo: 110, romanceScore: 70, nostalgiaScore: 60, confidenceScore: 85, cinematicScore: 75, peacefulScore: 35, danceScore: 90, darknessScore: 8, duration: "5:28", vibeTags: ["playfulDance", "streetFestival", "carefreeJoy", "quirkyFun"], lyricalThemes: ["mischief", "flirtation", "pureJoy"] },
  { title: "Zehnaseeb", artist: "Chinmayi Sripada & Shekhar Ravjiani", language: "Hindi", countryOrRegion: "IN", genre: "Bollywood Romantic", subgenre: "Acoustic Ballad", mood: "Romantic", secondaryMood: "Peaceful", energy: 46, tempo: 80, romanceScore: 98, nostalgiaScore: 82, confidenceScore: 55, cinematicScore: 85, peacefulScore: 90, danceScore: 30, darknessScore: 12, duration: "3:35", vibeTags: ["blessedLove", "pureDevotion", "softStrings", "warmSmile"], lyricalThemes: ["fortuneInLove", "gentleAffection", "destiny"] },
  { title: "Mast Magan", artist: "Arijit Singh & Chinmayi Sripada", language: "Hindi", countryOrRegion: "IN", genre: "Bollywood Sufi", subgenre: "Romantic", mood: "Romantic", secondaryMood: "Dreamy", energy: 56, tempo: 88, romanceScore: 96, nostalgiaScore: 78, confidenceScore: 65, cinematicScore: 88, peacefulScore: 82, danceScore: 40, darknessScore: 15, duration: "4:40", vibeTags: ["sufiTrance", "weddingSacred", "heartbeatPulse", "devotionalLove"], lyricalThemes: ["soulAbsorption", "enchantment", "devotion"] },
  { title: "Pee Loon", artist: "Mohit Chauhan", language: "Hindi", countryOrRegion: "IN", genre: "Bollywood Romantic", subgenre: "Sufi Pop", mood: "Romantic", secondaryMood: "Dreamy", energy: 50, tempo: 92, romanceScore: 98, nostalgiaScore: 90, confidenceScore: 55, cinematicScore: 85, peacefulScore: 88, danceScore: 30, darknessScore: 14, duration: "4:48", vibeTags: ["desertSunset", "sufiAcoustic", "classicBollywood", "romanticBliss"], lyricalThemes: ["drinkingInLove", "surrender", "sweetAffection"] },
  { title: "Tera Hone Laga Hoon", artist: "Atif Aslam & Alisha Chinai", language: "Hindi", countryOrRegion: "IN", genre: "Bollywood Romantic Pop", subgenre: "Pop Ballad", mood: "Romantic", secondaryMood: "Happy", energy: 65, tempo: 105, romanceScore: 95, nostalgiaScore: 88, confidenceScore: 70, cinematicScore: 80, peacefulScore: 70, danceScore: 65, darknessScore: 10, duration: "4:59", vibeTags: ["firstFallingInLove", "atifMagic", "2000sRomance", "goldenMemory"], lyricalThemes: ["belongingToYou", "transformation", "sweetSurprise"] },
  { title: "Jeena Jeena", artist: "Atif Aslam", language: "Hindi", countryOrRegion: "IN", genre: "Bollywood Ballad", subgenre: "Acoustic Soul", mood: "Romantic", secondaryMood: "Peaceful", energy: 44, tempo: 85, romanceScore: 96, nostalgiaScore: 85, confidenceScore: 55, cinematicScore: 86, peacefulScore: 90, danceScore: 25, darknessScore: 20, duration: "3:49", vibeTags: ["atifSoul", "warmBlanket", "heartfeltVows", "gentlePiano"], lyricalThemes: ["purposeInLove", "breathingTogether", "devotion"] },
  { title: "Tu Jane Na", artist: "Atif Aslam", language: "Hindi", countryOrRegion: "IN", genre: "Bollywood Romantic", subgenre: "Rock Ballad", mood: "Nostalgic", secondaryMood: "Cinematic", energy: 58, tempo: 95, romanceScore: 92, nostalgiaScore: 96, confidenceScore: 60, cinematicScore: 90, peacefulScore: 60, danceScore: 35, darknessScore: 45, duration: "5:38", vibeTags: ["unspokenLove", "painfulLonging", "classicAtif", "nostalgicRadio"], lyricalThemes: ["unspokenLove", "silentSuffering", "yearning"] },
  { title: "Raabta (Kehte Hain Khuda Ne)", artist: "Arijit Singh & Shreya Ghoshal", language: "Hindi", countryOrRegion: "IN", genre: "Bollywood Romantic", subgenre: "Acoustic Pop", mood: "Romantic", secondaryMood: "Dreamy", energy: 50, tempo: 86, romanceScore: 98, nostalgiaScore: 86, confidenceScore: 60, cinematicScore: 88, peacefulScore: 85, danceScore: 35, darknessScore: 12, duration: "4:04", vibeTags: ["destinedConnection", "soulmateVibe", "pureHarmony", "delicatePiano"], lyricalThemes: ["connectionAcrossLifetimes", "divinePlan", "harmony"] },
  { title: "Apna Bana Le", artist: "Arijit Singh & Sachin-Jigar", language: "Hindi", countryOrRegion: "IN", genre: "Bollywood Romantic", subgenre: "Pop Folk", mood: "Romantic", secondaryMood: "Nostalgic", energy: 58, tempo: 90, romanceScore: 98, nostalgiaScore: 80, confidenceScore: 65, cinematicScore: 85, peacefulScore: 78, danceScore: 45, darknessScore: 18, duration: "4:21", vibeTags: ["soulSurrender", "modernClassic", "heartfeltPleas", "warmAcoustic"], lyricalThemes: ["makeMeYours", "surrender", "unendingLove"] },
  { title: "Channa Mereya", artist: "Arijit Singh & Pritam", language: "Hindi", countryOrRegion: "IN", genre: "Bollywood Soul Ballad", subgenre: "Sufi", mood: "Cinematic", secondaryMood: "Nostalgic", energy: 60, tempo: 120, romanceScore: 92, nostalgiaScore: 98, confidenceScore: 50, cinematicScore: 98, peacefulScore: 45, danceScore: 25, darknessScore: 70, duration: "4:49", vibeTags: ["weddingHeartbreak", "legendaryAnthem", "tearfulFarewell", "sufiClimax"], lyricalThemes: ["goodbyeToLove", "sacredMemories", "bittersweetBlessing"] },
  { title: "Bulleya", artist: "Amit Mishra & Shilpa Rao", language: "Hindi", countryOrRegion: "IN", genre: "Sufi Rock", subgenre: "Bollywood Rock", mood: "Confident", secondaryMood: "Cinematic", energy: 88, tempo: 138, romanceScore: 75, nostalgiaScore: 55, confidenceScore: 92, cinematicScore: 95, peacefulScore: 20, danceScore: 60, darknessScore: 65, duration: "5:49", vibeTags: ["roaringGuitars", "sufiPassion", "furiousLove", "viennaStreets"], lyricalThemes: ["spiritualFire", "uncontainableDesire", "rebellion"] },
  { title: "Shayad", artist: "Arijit Singh & Pritam", language: "Hindi", countryOrRegion: "IN", genre: "Bollywood Romantic", subgenre: "Acoustic Pop", mood: "Romantic", secondaryMood: "Nostalgic", energy: 52, tempo: 92, romanceScore: 96, nostalgiaScore: 90, confidenceScore: 55, cinematicScore: 84, peacefulScore: 80, danceScore: 35, darknessScore: 22, duration: "4:07", vibeTags: ["maybeLove", "tenderConfession", "acousticWarmth", "sweetMelancholy"], lyricalThemes: ["hopefulHesitation", "gentleConfession", "purity"] },
  { title: "Ghar", artist: "Nikhita Gandhi & Mohit Chauhan", language: "Hindi", countryOrRegion: "IN", genre: "Acoustic Indie Pop", subgenre: "Bollywood", mood: "Peaceful", secondaryMood: "Romantic", energy: 40, tempo: 82, romanceScore: 92, nostalgiaScore: 85, confidenceScore: 50, cinematicScore: 82, peacefulScore: 96, danceScore: 25, darknessScore: 14, duration: "3:48", vibeTags: ["homeInYou", "sundayMorning", "lazySunlight", "whisperedLove"], lyricalThemes: ["homeIsYou", "quietSanctuary", "belonging"] },
  { title: "Aankhon Se Batana", artist: "Dikshant", language: "Hindi", countryOrRegion: "IN", genre: "Hindi Bedroom Pop", subgenre: "Acoustic", mood: "Cute", secondaryMood: "Romantic", energy: 46, tempo: 95, romanceScore: 94, nostalgiaScore: 70, confidenceScore: 50, cinematicScore: 70, peacefulScore: 88, danceScore: 50, darknessScore: 8, duration: "3:39", vibeTags: ["silentGlances", "firstCrush", "wholesomeReels", "gentleGuitar"], lyricalThemes: ["speakWithEyes", "unspokenChemistry", "innocence"] },
  { title: "Faasle", artist: "Aditya Rikhari", language: "Hindi", countryOrRegion: "IN", genre: "Hindi Indie Pop", subgenre: "Lo-Fi", mood: "Nostalgic", secondaryMood: "Dark", energy: 50, tempo: 98, romanceScore: 80, nostalgiaScore: 95, confidenceScore: 45, cinematicScore: 80, peacefulScore: 68, danceScore: 35, darknessScore: 58, duration: "3:02", vibeTags: ["distances", "midnightRegret", "rainyMetro", "indieHeart"], lyricalThemes: ["growingApart", "unbridgeableGap", "memories"] },
  { title: "Kya Karoon?", artist: "Zaeden", language: "Hindi", countryOrRegion: "IN", genre: "Hindi Indie Pop", subgenre: "Electropop", mood: "Happy", secondaryMood: "Cute", energy: 75, tempo: 112, romanceScore: 88, nostalgiaScore: 65, confidenceScore: 75, cinematicScore: 72, peacefulScore: 60, danceScore: 82, darknessScore: 10, duration: "2:58", vibeTags: ["puppyLove", "breezyDrive", "modernRomance", "feelGood"], lyricalThemes: ["crushButterflies", "playfulConfession", "happiness"] },
  { title: "Tere Bina", artist: "Zaeden", language: "Hindi", countryOrRegion: "IN", genre: "Hindi Indie Pop", subgenre: "Acoustic Pop", mood: "Romantic", secondaryMood: "Dreamy", energy: 54, tempo: 96, romanceScore: 92, nostalgiaScore: 78, confidenceScore: 65, cinematicScore: 78, peacefulScore: 80, danceScore: 45, darknessScore: 18, duration: "3:10", vibeTags: ["withoutYou", "softSunlight", "intimateVoice", "modernAcoustic"], lyricalThemes: ["emptinessWithoutYou", "gentlePromise", "warmth"] },
  { title: "Subhanallah", artist: "Sreerama Chandra & Shilpa Rao", language: "Hindi", countryOrRegion: "IN", genre: "Bollywood Romantic", subgenre: "Folk Pop", mood: "Romantic", secondaryMood: "Happy", energy: 62, tempo: 100, romanceScore: 95, nostalgiaScore: 75, confidenceScore: 70, cinematicScore: 85, peacefulScore: 75, danceScore: 60, darknessScore: 8, duration: "4:09", vibeTags: ["snowInManali", "stunningBeauty", "praiseOfLove", "breezyRomance"], lyricalThemes: ["aweOfBeauty", "fallingHard", "snowyHolidays"] },
  { title: "Main Rahoon Ya Na Rahoon", artist: "Armaan Malik", language: "Hindi", countryOrRegion: "IN", genre: "Bollywood Ballad", subgenre: "Romantic Soul", mood: "Romantic", secondaryMood: "Cinematic", energy: 48, tempo: 85, romanceScore: 96, nostalgiaScore: 90, confidenceScore: 50, cinematicScore: 90, peacefulScore: 82, danceScore: 25, darknessScore: 35, duration: "5:08", vibeTags: ["eternalLove", "emotionalVows", "armaanMelody", "classicRomance"], lyricalThemes: ["loveOutlivingLife", "unfadingBond", "devotion"] },
  { title: "Iktara", artist: "Kavita Seth & Tochi Raina", language: "Hindi", countryOrRegion: "IN", genre: "Bollywood Sufi", subgenre: "Folk", mood: "Dreamy", secondaryMood: "Romantic", energy: 46, tempo: 88, romanceScore: 94, nostalgiaScore: 92, confidenceScore: 50, cinematicScore: 88, peacefulScore: 92, danceScore: 30, darknessScore: 15, duration: "4:13", vibeTags: ["singleStringSufi", "bombayMonsoon", "wakeUpSid", "gentleSoul"], lyricalThemes: ["wanderingHeart", "sufiAwakening", "serenity"] },
  { title: "Maan Meri Jaan", artist: "King", language: "Hindi", countryOrRegion: "IN", genre: "Pop Rap / R&B", subgenre: "Desi Pop", mood: "Romantic", secondaryMood: "Confident", energy: 72, tempo: 96, romanceScore: 94, nostalgiaScore: 65, confidenceScore: 88, cinematicScore: 82, peacefulScore: 55, danceScore: 75, darknessScore: 25, duration: "3:14", vibeTags: ["viralReels", "heartfeltConfession", "modernDesiPop", "passionateVibe"], lyricalThemes: ["listenMySoul", "unyieldingLove", "loyalty"] },
  { title: "Tu Aake Dekhle", artist: "King", language: "Hindi", countryOrRegion: "IN", genre: "Hip-Hop Pop", subgenre: "Desi Trap Pop", mood: "Confident", secondaryMood: "Romantic", energy: 76, tempo: 98, romanceScore: 85, nostalgiaScore: 60, confidenceScore: 92, cinematicScore: 80, peacefulScore: 50, danceScore: 80, darknessScore: 35, duration: "4:30", vibeTags: ["midnightCruising", "comeAndWitness", "smoothDesiTrap", "swaggerRomance"], lyricalThemes: ["witnessMyWorld", "passion", "confidence"] },
  { title: "Ghungroo", artist: "Arijit Singh & Shilpa Rao", language: "Hindi", countryOrRegion: "IN", genre: "Bollywood Dance", subgenre: "Nu-Disco / Funk", mood: "Energetic", secondaryMood: "Happy", energy: 90, tempo: 118, romanceScore: 72, nostalgiaScore: 40, confidenceScore: 90, cinematicScore: 85, peacefulScore: 20, danceScore: 98, darknessScore: 8, duration: "5:02", vibeTags: ["beachClub", "dancingShoes", "sunlitCocktails", "discoFunk"], lyricalThemes: ["lossOfInhibitions", "dancefloorCelebration", "flirtation"] },
  { title: "Badtameez Dil", artist: "Benny Dayal & Shefali Alvares", language: "Hindi", countryOrRegion: "IN", genre: "Bollywood Dance Pop", subgenre: "Brass Funk", mood: "Energetic", secondaryMood: "Happy", energy: 95, tempo: 144, romanceScore: 55, nostalgiaScore: 75, confidenceScore: 95, cinematicScore: 88, peacefulScore: 10, danceScore: 99, darknessScore: 5, duration: "4:12", vibeTags: ["partyAnthem", "shamelessHeart", "brassExplosion", "celebrationVibe"], lyricalThemes: ["unrulyHeart", "partyEuphoria", "celebration"] },
  { title: "Nashe Si Chadh Gayi", artist: "Arijit Singh", language: "Hindi", countryOrRegion: "IN", genre: "Dance Pop", subgenre: "French Electro-Bollywood", mood: "Energetic", secondaryMood: "Confident", energy: 88, tempo: 114, romanceScore: 80, nostalgiaScore: 50, confidenceScore: 90, cinematicScore: 82, peacefulScore: 25, danceScore: 95, darknessScore: 12, duration: "3:57", vibeTags: ["parisStreets", "intoxicationOfLove", "breezyClub", "dancefloorCatchy"], lyricalThemes: ["headyLove", "intoxication", "attraction"] },

  // ================= KOREAN (25+ songs) =================
  { title: "Ditto", artist: "NewJeans", language: "Korean", countryOrRegion: "KR", genre: "K-Pop", subgenre: "Baltimore Club / R&B", mood: "Dreamy", secondaryMood: "Nostalgic", energy: 58, tempo: 134, romanceScore: 85, nostalgiaScore: 96, confidenceScore: 50, cinematicScore: 90, peacefulScore: 75, danceScore: 75, darknessScore: 35, duration: "3:05", vibeTags: ["y2kAesthetic", "baltimoreClub", "wistfulCamcorder", "winterSchoolyard"], lyricalThemes: ["wistfulness", "yearning", "youthMemories"] },
  { title: "OMG", artist: "NewJeans", language: "Korean", countryOrRegion: "KR", genre: "K-Pop", subgenre: "UK Garage / R&B", mood: "Happy", secondaryMood: "Cute", energy: 82, tempo: 127, romanceScore: 80, nostalgiaScore: 60, confidenceScore: 75, cinematicScore: 70, peacefulScore: 45, danceScore: 92, darknessScore: 10, duration: "3:32", vibeTags: ["trendyDance", "cuteConfusion", "groovyBass", "viralReels"], lyricalThemes: ["overwhelmedByLove", "butterflies", "excitement"] },
  { title: "Hype Boy", artist: "NewJeans", language: "Korean", countryOrRegion: "KR", genre: "K-Pop", subgenre: "Contemporary R&B", mood: "Confident", secondaryMood: "Happy", energy: 85, tempo: 100, romanceScore: 78, nostalgiaScore: 65, confidenceScore: 90, cinematicScore: 72, peacefulScore: 40, danceScore: 95, darknessScore: 10, duration: "2:59", vibeTags: ["summerCrush", "effortlessCool", "nostalgicRnb", "sunnyDay"], lyricalThemes: ["crushSwagger", "confidence", "youthFreedom"] },
  { title: "Love Lee", artist: "AKMU", language: "Korean", countryOrRegion: "KR", genre: "K-Pop", subgenre: "Acoustic Pop", mood: "Cute", secondaryMood: "Happy", energy: 80, tempo: 118, romanceScore: 90, nostalgiaScore: 60, confidenceScore: 80, cinematicScore: 65, peacefulScore: 60, danceScore: 85, darknessScore: 5, duration: "2:59", vibeTags: ["playfulHarmony", "pastelAesthetic", "cheerfulWhistle", "pureRomance"], lyricalThemes: ["lovelyLove", "sweetness", "laughter"] },
  { title: "Through the Night", artist: "IU", language: "Korean", countryOrRegion: "KR", genre: "K-Ballad", subgenre: "Acoustic Folk", mood: "Peaceful", secondaryMood: "Romantic", energy: 28, tempo: 78, romanceScore: 96, nostalgiaScore: 95, confidenceScore: 35, cinematicScore: 88, peacefulScore: 99, danceScore: 15, darknessScore: 20, duration: "4:13", vibeTags: ["midnightLullaby", "candlelight", "iuVoice", "delicateAcoustic"], lyricalThemes: ["nightLetter", "gentleConfession", "wishingPeace"] },
  { title: "Palette", artist: "IU & G-DRAGON", language: "Korean", countryOrRegion: "KR", genre: "K-Pop", subgenre: "Synth Pop", mood: "Elegant", secondaryMood: "Confident", energy: 60, tempo: 100, romanceScore: 60, nostalgiaScore: 85, confidenceScore: 85, cinematicScore: 80, peacefulScore: 75, danceScore: 65, darknessScore: 15, duration: "3:37", vibeTags: ["twentyFive", "pastelColors", "selfDiscovery", "chicElegance"], lyricalThemes: ["selfAcceptance", "favoriteColors", "growingUp"] },
  { title: "Eight", artist: "IU & SUGA", language: "Korean", countryOrRegion: "KR", genre: "K-Rock", subgenre: "Pop Rock", mood: "Nostalgic", secondaryMood: "Dreamy", energy: 78, tempo: 120, romanceScore: 70, nostalgiaScore: 98, confidenceScore: 70, cinematicScore: 90, peacefulScore: 55, danceScore: 70, darknessScore: 30, duration: "2:48", vibeTags: ["islandOfYouth", "goldenSunset", "wistfulMemories", "upliftingRock"], lyricalThemes: ["lostYouth", "meetingAgain", "preciousMemories"] },
  { title: "Spring Day", artist: "BTS", language: "Korean", countryOrRegion: "KR", genre: "K-Pop", subgenre: "Alt-Rock / Hip-Hop", mood: "Nostalgic", secondaryMood: "Cinematic", energy: 65, tempo: 108, romanceScore: 75, nostalgiaScore: 99, confidenceScore: 60, cinematicScore: 98, peacefulScore: 65, danceScore: 45, darknessScore: 40, duration: "4:34", vibeTags: ["snowTrain", "cherryBlossomWaiting", "friendshipMasterpiece", "deepEmotion"], lyricalThemes: ["missingAFriend", "winterPassing", "enduringHope"] },
  { title: "Life Goes On", artist: "BTS", language: "Korean", countryOrRegion: "KR", genre: "K-Pop", subgenre: "Alt-R&B", mood: "Peaceful", secondaryMood: "Nostalgic", energy: 50, tempo: 81, romanceScore: 65, nostalgiaScore: 88, confidenceScore: 65, cinematicScore: 82, peacefulScore: 95, danceScore: 40, darknessScore: 20, duration: "3:27", vibeTags: ["gentleComfort", "cozyMorningRoom", "pandemicComfort", "softAcoustic"], lyricalThemes: ["reassurance", "lifeContinues", "healing"] },
  { title: "Euphoria", artist: "Jungkook (BTS)", language: "Korean", countryOrRegion: "KR", genre: "K-Pop", subgenre: "Future Bass", mood: "Happy", secondaryMood: "Dreamy", energy: 78, tempo: 128, romanceScore: 92, nostalgiaScore: 80, confidenceScore: 75, cinematicScore: 90, peacefulScore: 60, danceScore: 80, darknessScore: 10, duration: "3:49", vibeTags: ["blueSkyFly", "goldenHourJoy", "euphoricBuild", "pureRomance"], lyricalThemes: ["utopiaInLove", "sunlitWorld", "uncontainableJoy"] },
  { title: "Seven", artist: "Jungkook & Latto", language: "English/Korean", countryOrRegion: "KR", genre: "UK Garage Pop", subgenre: "Pop R&B", mood: "Confident", secondaryMood: "Energetic", energy: 88, tempo: 125, romanceScore: 90, nostalgiaScore: 40, confidenceScore: 95, cinematicScore: 75, peacefulScore: 30, danceScore: 96, darknessScore: 12, duration: "3:04", vibeTags: ["sevenDaysAWeek", "smoothGarage", "viralDance", "summerFlirt"], lyricalThemes: ["relentlessRomance", "devotionEveryDay", "playfulness"] },
  { title: "Like Crazy", artist: "Jimin (BTS)", language: "Korean", countryOrRegion: "KR", genre: "Synth-Pop", subgenre: "Darkwave", mood: "Cinematic", secondaryMood: "Dark", energy: 76, tempo: 120, romanceScore: 78, nostalgiaScore: 75, confidenceScore: 75, cinematicScore: 92, peacefulScore: 45, danceScore: 80, darknessScore: 65, duration: "3:32", vibeTags: ["neonClubHaze", "glitteringSorrow", "cinematicSynth", "nightWhispers"], lyricalThemes: ["escapingPain", "dreamReflection", "intenseNight"] },
  { title: "Love Me Again", artist: "V (BTS)", language: "Korean", countryOrRegion: "KR", genre: "R&B / Soul", subgenre: "Neo-Soul", mood: "Romantic", secondaryMood: "Nostalgic", energy: 45, tempo: 110, romanceScore: 94, nostalgiaScore: 92, confidenceScore: 50, cinematicScore: 85, peacefulScore: 82, danceScore: 35, darknessScore: 40, duration: "3:02", vibeTags: ["warmGoldShimmer", "vintageSoul", "vocalDeepTone", "heartfeltPleas"], lyricalThemes: ["pleaForLove", "rememberingPast", "unfadingFeelings"] },
  { title: "Slow Dancing", artist: "V (BTS)", language: "Korean", countryOrRegion: "KR", genre: "Soul / R&B", subgenre: "Flute Soul", mood: "Peaceful", secondaryMood: "Romantic", energy: 42, tempo: 78, romanceScore: 92, nostalgiaScore: 88, confidenceScore: 55, cinematicScore: 84, peacefulScore: 96, danceScore: 40, darknessScore: 15, duration: "3:07", vibeTags: ["fluteSolo", "beachSunset", "laidbackSoul", "gentleSway"], lyricalThemes: ["slowDancingTogether", "lazyAfternoon", "serenity"] },
  { title: "Standing Next to You", artist: "Jungkook", language: "English/Korean", countryOrRegion: "KR", genre: "Disco Funk", subgenre: "Pop Soul", mood: "Confident", secondaryMood: "Energetic", energy: 92, tempo: 106, romanceScore: 85, nostalgiaScore: 50, confidenceScore: 98, cinematicScore: 88, peacefulScore: 15, danceScore: 96, darknessScore: 25, duration: "3:26", vibeTags: ["michaelJacksonVibe", "brassExplosion", "goldenArmor", "pureSwagger"], lyricalThemes: ["loyaltyThroughFire", "divineBond", "greatness"] },
  { title: "Some", artist: "Soyou & Junggigo", language: "Korean", countryOrRegion: "KR", genre: "K-Pop", subgenre: "Acoustic R&B Duet", mood: "Cute", secondaryMood: "Romantic", energy: 62, tempo: 95, romanceScore: 95, nostalgiaScore: 80, confidenceScore: 60, cinematicScore: 68, peacefulScore: 78, danceScore: 60, darknessScore: 8, duration: "3:31", vibeTags: ["somethingBetweenUs", "flirtatiousDuet", "caféDate", "koreanRomcom"], lyricalThemes: ["situationship", "unspokenLove", "sweetAnticipation"] },
  { title: "Any Song", artist: "ZICO", language: "Korean", countryOrRegion: "KR", genre: "K-Hip Hop", subgenre: "Jazz Pop", mood: "Happy", secondaryMood: "Energetic", energy: 82, tempo: 106, romanceScore: 35, nostalgiaScore: 45, confidenceScore: 85, cinematicScore: 65, peacefulScore: 35, danceScore: 95, darknessScore: 10, duration: "3:47", vibeTags: ["viralTikTokChallenge", "pianoGroove", "casualCool", "houseParty"], lyricalThemes: ["boredomRelief", "mindlessDancing", "goodVibes"] },

  // ================= JAPANESE (20+ songs) =================
  { title: "Sparkle (スパークル)", artist: "RADWIMPS", language: "Japanese", countryOrRegion: "JP", genre: "J-Rock", subgenre: "Piano Ballad", mood: "Cinematic", secondaryMood: "Dreamy", energy: 60, tempo: 124, romanceScore: 95, nostalgiaScore: 98, confidenceScore: 55, cinematicScore: 99, peacefulScore: 75, danceScore: 25, darknessScore: 25, duration: "6:49", vibeTags: ["animeAesthetic", "pianoEthereal", "twilightComet", "yourName"], lyricalThemes: ["destinedLovers", "meteorShower", "timelessPledge"] },
  { title: "Nandemonaiya", artist: "RADWIMPS", language: "Japanese", countryOrRegion: "JP", genre: "J-Rock", subgenre: "Ballad", mood: "Nostalgic", secondaryMood: "Romantic", energy: 50, tempo: 88, romanceScore: 92, nostalgiaScore: 99, confidenceScore: 45, cinematicScore: 96, peacefulScore: 80, danceScore: 20, darknessScore: 30, duration: "5:42", vibeTags: ["tokyoSunset", "passingTrain", "heartacheToJoy", "animeSoundtrack"], lyricalThemes: ["tearsOfRelief", "soulReunion", "lifeMeaning"] },
  { title: "Plastic Love", artist: "Mariya Takeuchi", language: "Japanese", countryOrRegion: "JP", genre: "City Pop", subgenre: "Funk / Disco", mood: "Elegant", secondaryMood: "Nostalgic", energy: 72, tempo: 105, romanceScore: 75, nostalgiaScore: 99, confidenceScore: 80, cinematicScore: 90, peacefulScore: 60, danceScore: 85, darknessScore: 40, duration: "4:53", vibeTags: ["cityPop80s", "tokyoNeon", "retroCocktail", "bittersweetGroove"], lyricalThemes: ["fakeRomance", "lonelyNightclub", "sophistication"] },
  { title: "Stay With Me (真夜中のドア)", artist: "Miki Matsubara", language: "Japanese", countryOrRegion: "JP", genre: "City Pop", subgenre: "Jazz Funk", mood: "Nostalgic", secondaryMood: "Romantic", energy: 75, tempo: 108, romanceScore: 88, nostalgiaScore: 99, confidenceScore: 75, cinematicScore: 88, peacefulScore: 55, danceScore: 84, darknessScore: 35, duration: "4:34", vibeTags: ["midnightDoor", "80sVinyl", "retroRomance", "cityLights"], lyricalThemes: ["pleaToStay", "cozyNight", "timelessNostalgia"] },
  { title: "First Love", artist: "Hikaru Utada", language: "Japanese", countryOrRegion: "JP", genre: "J-Pop", subgenre: "R&B Ballad", mood: "Nostalgic", secondaryMood: "Romantic", energy: 40, tempo: 90, romanceScore: 98, nostalgiaScore: 99, confidenceScore: 40, cinematicScore: 94, peacefulScore: 80, danceScore: 20, darknessScore: 38, duration: "4:17", vibeTags: ["legendaryBallad", "snowyHokkaido", "cigaretteTaste", "firstLoveTears"], lyricalThemes: ["firstLoveMemory", "cherishedPain", "unforgettable"] },
  { title: "Lemon", artist: "Kenshi Yonezu", language: "Japanese", countryOrRegion: "JP", genre: "J-Pop", subgenre: "Orchestral Pop", mood: "Cinematic", secondaryMood: "Nostalgic", energy: 68, tempo: 95, romanceScore: 82, nostalgiaScore: 98, confidenceScore: 65, cinematicScore: 98, peacefulScore: 50, danceScore: 45, darknessScore: 65, duration: "4:15", vibeTags: ["bitterLemonScent", "griefToLight", "unforgettableMasterpiece", "dramaticViolins"], lyricalThemes: ["grief", "memoryLikeLemon", "eternalLight"] },
  { title: "Idol (アイドル)", artist: "YOASOBI", language: "Japanese", countryOrRegion: "JP", genre: "J-Pop", subgenre: "Hyperpop / Dance", mood: "Energetic", secondaryMood: "Confident", energy: 98, tempo: 166, romanceScore: 50, nostalgiaScore: 30, confidenceScore: 98, cinematicScore: 92, peacefulScore: 5, danceScore: 99, darknessScore: 50, duration: "3:33", vibeTags: ["hyperEnergy", "stageLights", "masterOfLies", "animeOshiNoKo"], lyricalThemes: ["idolPersona", "secretBehindSmile", "ferociousPassion"] },
  { title: "Racing into the Night (夜に駆ける)", artist: "YOASOBI", language: "Japanese", countryOrRegion: "JP", genre: "J-Pop", subgenre: "Speed Synth Pop", mood: "Energetic", secondaryMood: "Dark", energy: 92, tempo: 130, romanceScore: 65, nostalgiaScore: 70, confidenceScore: 80, cinematicScore: 90, peacefulScore: 15, danceScore: 95, darknessScore: 75, duration: "4:21", vibeTags: ["pianoSprint", "midnightLeap", "fastPacedAesthetic", "animeVibe"], lyricalThemes: ["intoTheNight", "beckoningShadow", "unbreakablePact"] },

  // ================= SPANISH (25+ songs) =================
  { title: "Telepatía", artist: "Kali Uchis", language: "Spanish", countryOrRegion: "CO/US", genre: "Latin R&B", subgenre: "Neo-Soul", mood: "Dreamy", secondaryMood: "Romantic", energy: 48, tempo: 84, romanceScore: 96, nostalgiaScore: 80, confidenceScore: 75, cinematicScore: 85, peacefulScore: 85, danceScore: 60, darknessScore: 20, duration: "2:40", vibeTags: ["silkPastel", "telepathicLove", "sensualBreeze", "bedroomRnb"], lyricalThemes: ["telepathicConnection", "longDistanceSensuality", "intimacy"] },
  { title: "Despacito", artist: "Luis Fonsi & Daddy Yankee", language: "Spanish", countryOrRegion: "PR", genre: "Reggaeton", subgenre: "Latin Pop", mood: "Energetic", secondaryMood: "Romantic", energy: 88, tempo: 89, romanceScore: 90, nostalgiaScore: 60, confidenceScore: 90, cinematicScore: 80, peacefulScore: 30, danceScore: 99, darknessScore: 10, duration: "3:48", vibeTags: ["puertoRicoSun", "beachParty", "iconicReggaeton", "summerHeat"], lyricalThemes: ["slowSensualLove", "beachRhythm", "passion"] },
  { title: "Bailando", artist: "Enrique Iglesias & Gente de Zona", language: "Spanish", countryOrRegion: "ES/CU", genre: "Latin Pop", subgenre: "Flamenco Pop", mood: "Happy", secondaryMood: "Energetic", energy: 92, tempo: 91, romanceScore: 85, nostalgiaScore: 65, confidenceScore: 92, cinematicScore: 85, peacefulScore: 20, danceScore: 98, darknessScore: 8, duration: "4:03", vibeTags: ["flamencoStomp", "havanaStreets", "pureCelebration", "summerEuphoria"], lyricalThemes: ["dancingInTheStreet", "irresistibleAttraction", "joy"] },
  { title: "Dákiti", artist: "Bad Bunny & Jhayco", language: "Spanish", countryOrRegion: "PR", genre: "Reggaeton", subgenre: "Afro-House Infused", mood: "Confident", secondaryMood: "Dreamy", energy: 78, tempo: 110, romanceScore: 82, nostalgiaScore: 60, confidenceScore: 94, cinematicScore: 85, peacefulScore: 50, danceScore: 95, darknessScore: 30, duration: "3:25", vibeTags: ["caribbeanNight", "luxuryYacht", "smoothSubBass", "clubVibe"], lyricalThemes: ["islandNightlife", "mutualAttraction", "luxury"] },
  { title: "Ojitos Lindos", artist: "Bad Bunny & Bomba Estéreo", language: "Spanish", countryOrRegion: "PR/CO", genre: "Latin Indie", subgenre: "Electropop Tropical", mood: "Romantic", secondaryMood: "Happy", energy: 70, tempo: 80, romanceScore: 98, nostalgiaScore: 78, confidenceScore: 75, cinematicScore: 88, peacefulScore: 75, danceScore: 80, darknessScore: 12, duration: "4:18", vibeTags: ["prettyEyes", "breezyCoast", "warmAffection", "goldenHourBeach"], lyricalThemes: ["prettyEyes", "unconditionalLove", "sanctuary"] },
  { title: "Mon Amour (Remix)", artist: "zoilo & Aitana", language: "Spanish", countryOrRegion: "ES", genre: "Pop Rock", subgenre: "Indie Pop", mood: "Happy", secondaryMood: "Romantic", energy: 85, tempo: 130, romanceScore: 92, nostalgiaScore: 55, confidenceScore: 80, cinematicScore: 70, peacefulScore: 40, danceScore: 90, darknessScore: 5, duration: "2:59", vibeTags: ["euphoricCrush", "sunflowerEnergy", "singalongChorus", "spainSummer"], lyricalThemes: ["declarationOfLove", "brightSmile", "boundlessJoy"] },

  // ================= PUNJABI (20+ songs) =================
  { title: "Pasoori", artist: "Ali Sethi & Shae Gill", language: "Punjabi", countryOrRegion: "PK", genre: "Folk Fusion", subgenre: "Coke Studio", mood: "Romantic", secondaryMood: "Cinematic", energy: 78, tempo: 122, romanceScore: 92, nostalgiaScore: 85, confidenceScore: 85, cinematicScore: 94, peacefulScore: 55, danceScore: 88, darknessScore: 30, duration: "3:44", vibeTags: ["cokeStudioLegend", "punjabiFlamenco", "transcendentMelody", "culturalMasterpiece"], lyricalThemes: ["longingOverBorders", "fireOfLove", "passion"] },
  { title: "Lover", artist: "Diljit Dosanjh", language: "Punjabi", countryOrRegion: "IN", genre: "Punjabi Pop", subgenre: "Synthwave Pop", mood: "Romantic", secondaryMood: "Happy", energy: 84, tempo: 110, romanceScore: 95, nostalgiaScore: 60, confidenceScore: 90, cinematicScore: 82, peacefulScore: 45, danceScore: 94, darknessScore: 10, duration: "3:10", vibeTags: ["retroSynthwave", "diljitCharm", "pureRomance", "goldenSunsetCruising"], lyricalThemes: ["loverDevotion", "modernRomance", "sweetConfession"] },
  { title: "Proper Patola", artist: "Diljit Dosanjh & Badshah", language: "Punjabi", countryOrRegion: "IN", genre: "Punjabi Urban", subgenre: "Hip-Hop", mood: "Confident", secondaryMood: "Energetic", energy: 90, tempo: 98, romanceScore: 70, nostalgiaScore: 65, confidenceScore: 98, cinematicScore: 80, peacefulScore: 15, danceScore: 96, darknessScore: 20, duration: "3:40", vibeTags: ["urbanSwag", "punjabiStyle", "heavyBass", "weddingBanger"], lyricalThemes: ["glamour", "admiration", "highFashion"] },
  { title: "Brown Munde", artist: "AP Dhillon, Gurinder Gill & Shinda Kahlon", language: "Punjabi", countryOrRegion: "CA/IN", genre: "Punjabi Hip-Hop", subgenre: "Trap", mood: "Confident", secondaryMood: "Dark", energy: 88, tempo: 90, romanceScore: 25, nostalgiaScore: 50, confidenceScore: 99, cinematicScore: 85, peacefulScore: 20, danceScore: 90, darknessScore: 70, duration: "4:27", vibeTags: ["brownPride", "hoodVibes", "trapAnthem", "midnightConvoy"], lyricalThemes: ["brotherhood", "culturalPride", "dominance"] },
  { title: "Excuses", artist: "AP Dhillon & Gurinder Gill", language: "Punjabi", countryOrRegion: "CA/IN", genre: "Punjabi R&B", subgenre: "Synth Pop", mood: "Nostalgic", secondaryMood: "Romantic", energy: 74, tempo: 112, romanceScore: 88, nostalgiaScore: 90, confidenceScore: 75, cinematicScore: 85, peacefulScore: 50, danceScore: 85, darknessScore: 40, duration: "2:56", vibeTags: ["brokenPromises", "kehndiHundiSi", "viralTrend", "smoothSynths"], lyricalThemes: ["heartbreakExcuses", "promisesBroken", "lateNightRegret"] },
  { title: "Insane", artist: "AP Dhillon, Gurinder Gill & Shinda Kahlon", language: "Punjabi", countryOrRegion: "CA/IN", genre: "Punjabi Hip-Hop", subgenre: "Trap", mood: "Confident", secondaryMood: "Dark", energy: 86, tempo: 92, romanceScore: 40, nostalgiaScore: 40, confidenceScore: 98, cinematicScore: 84, peacefulScore: 20, danceScore: 88, darknessScore: 75, duration: "3:26", vibeTags: ["bossLevel", "darkAlleyLights", "unapologetic", "deepSubBass"], lyricalThemes: ["power", "insanity", "status"] },

  // ================= TAMIL (20+ songs) =================
  { title: "Megham Karukatha", artist: "Dhanush & Anirudh Ravichander", language: "Tamil", countryOrRegion: "IN", genre: "Tamil Pop", subgenre: "Acoustic Rain", mood: "Dreamy", secondaryMood: "Happy", energy: 65, tempo: 110, romanceScore: 94, nostalgiaScore: 80, confidenceScore: 70, cinematicScore: 85, peacefulScore: 82, danceScore: 75, darknessScore: 12, duration: "4:21", vibeTags: ["rainClouds", "monsoonBreeze", "dhanushVibe", "pureRomance"], lyricalThemes: ["darkRainClouds", "heartFlutter", "monsoonAffection"] },
  { title: "Arabic Kuthu - Halamithi Habibo", artist: "Anirudh Ravichander & Jonita Gandhi", language: "Tamil", countryOrRegion: "IN", genre: "Tamil Dance Pop", subgenre: "Arabic Fusion", mood: "Energetic", secondaryMood: "Confident", energy: 95, tempo: 125, romanceScore: 80, nostalgiaScore: 35, confidenceScore: 95, cinematicScore: 90, peacefulScore: 10, danceScore: 99, darknessScore: 15, duration: "4:39", vibeTags: ["thalapathyVijay", "globalDanceChallenge", "arabicRhythm", "festiveBlast"], lyricalThemes: ["belovedHabibi", "danceCelebration", "enchantment"] },
  { title: "Rowdy Baby", artist: "Dhanush & Dhee", language: "Tamil", countryOrRegion: "IN", genre: "Tamil Kuthu Pop", subgenre: "Folk Dance", mood: "Happy", secondaryMood: "Energetic", energy: 96, tempo: 108, romanceScore: 85, nostalgiaScore: 60, confidenceScore: 92, cinematicScore: 85, peacefulScore: 15, danceScore: 99, darknessScore: 8, duration: "4:44", vibeTags: ["billionViews", "sensationalKuthu", "playfulFlirtation", "pureEnergy"], lyricalThemes: ["rowdyRomance", "playfulLove", "streetDance"] },
  { title: "Enna Sona", artist: "A.R. Rahman & Arijit Singh", language: "Tamil/Hindi", countryOrRegion: "IN", genre: "Sufi Pop", subgenre: "Acoustic", mood: "Romantic", secondaryMood: "Peaceful", energy: 45, tempo: 82, romanceScore: 98, nostalgiaScore: 85, confidenceScore: 50, cinematicScore: 86, peacefulScore: 94, danceScore: 25, darknessScore: 12, duration: "3:33", vibeTags: ["goldenGaze", "rahmanMasterpiece", "pureBeauty", "tenderVows"], lyricalThemes: ["unfathomableBeauty", "gentleAffection", "gratitude"] },

  // ================= TELUGU (20+ songs) =================
  { title: "Samajavaragamana", artist: "Sid Sriram & Thaman S", language: "Telugu", countryOrRegion: "IN", genre: "Telugu Classical Fusion", subgenre: "Romantic Pop", mood: "Romantic", secondaryMood: "Elegant", energy: 58, tempo: 88, romanceScore: 98, nostalgiaScore: 85, confidenceScore: 70, cinematicScore: 92, peacefulScore: 85, danceScore: 45, darknessScore: 12, duration: "3:41", vibeTags: ["alluArjunHit", "classicalRagaFusion", "sidSriramMagic", "timelessTeluguRomance"], lyricalThemes: ["gracefulGait", "poeticAdmiration", "unrivaledElegance"] },
  { title: "Inkem Inkem Inkem Kaavaale", artist: "Sid Sriram & Gopi Sundar", language: "Telugu", countryOrRegion: "IN", genre: "Telugu Melody", subgenre: "Carnatic Acoustic", mood: "Romantic", secondaryMood: "Peaceful", energy: 52, tempo: 85, romanceScore: 98, nostalgiaScore: 88, confidenceScore: 60, cinematicScore: 90, peacefulScore: 92, danceScore: 35, darknessScore: 10, duration: "4:28", vibeTags: ["geethaGovindam", "sacredMelody", "templeVibes", "pureDevotion"], lyricalThemes: ["whatMoreCouldIWant", "completeInYou", "gentleJoy"] },
  { title: "Butta Bomma", artist: "Armaan Malik & Thaman S", language: "Telugu", countryOrRegion: "IN", genre: "Telugu Dance Pop", subgenre: "Folk Melody", mood: "Happy", secondaryMood: "Cute", energy: 85, tempo: 102, romanceScore: 92, nostalgiaScore: 65, confidenceScore: 85, cinematicScore: 80, peacefulScore: 40, danceScore: 96, darknessScore: 6, duration: "3:18", vibeTags: ["dollOfJoy", "alluArjunFootwork", "catchyWhistle", "celebrationSmile"], lyricalThemes: ["preciousDoll", "delightInLove", "cheerfulAffection"] },
  { title: "Naatu Naatu", artist: "Rahul Sipligunj, Kaala Bhairava & M.M. Keeravaani", language: "Telugu", countryOrRegion: "IN", genre: "Folk Dance", subgenre: "Cinematic High Energy", mood: "Energetic", secondaryMood: "Confident", energy: 99, tempo: 150, romanceScore: 20, nostalgiaScore: 40, confidenceScore: 99, cinematicScore: 99, peacefulScore: 5, danceScore: 100, darknessScore: 15, duration: "3:35", vibeTags: ["oscarWinner", "unstoppableStomp", "rawIndianEnergy", "danceWar"], lyricalThemes: ["indomitableSpirit", "earthyFolkPride", "limitlessEnergy"] },

  // ================= FRENCH (15+ songs) =================
  { title: "Dernière danse", artist: "Indila", language: "French", countryOrRegion: "FR", genre: "Chanson / Pop", subgenre: "Orchestral Pop", mood: "Cinematic", secondaryMood: "Dark", energy: 65, tempo: 110, romanceScore: 78, nostalgiaScore: 92, confidenceScore: 70, cinematicScore: 98, peacefulScore: 45, danceScore: 50, darknessScore: 72, duration: "3:43", vibeTags: ["parisRain", "melodramaticViolins", "monumentalChanson", "stormySky"], lyricalThemes: ["lastDance", "lonelinessInParis", "sorrow"] },
  { title: "Tourner Dans Le Vide", artist: "Indila", language: "French", countryOrRegion: "FR", genre: "Orchestral Pop", subgenre: "Cinematic", mood: "Cinematic", secondaryMood: "Nostalgic", energy: 72, tempo: 128, romanceScore: 82, nostalgiaScore: 90, confidenceScore: 75, cinematicScore: 96, peacefulScore: 35, danceScore: 65, darknessScore: 60, duration: "4:06", vibeTags: ["spinningInVoid", "sculptorGrief", "dramaticCrescendo", "gothicElegance"], lyricalThemes: ["spinningEmpty", "lostSculptor", "enduringLove"] },
  { title: "Je te laisserai des mots", artist: "Patrick Watson", language: "French", countryOrRegion: "CA", genre: "Neo-Classical", subgenre: "Piano Ambient", mood: "Peaceful", secondaryMood: "Dreamy", energy: 20, tempo: 70, romanceScore: 94, nostalgiaScore: 96, confidenceScore: 25, cinematicScore: 95, peacefulScore: 99, danceScore: 10, darknessScore: 35, duration: "2:40", vibeTags: ["leavesOfPaper", "gentlePianoTear", "tenderFarewell", "autumnRoom"], lyricalThemes: ["leavingNotesForYou", "silentPresence", "softFarewell"] },
  { title: "La vie en rose", artist: "Édith Piaf", language: "French", countryOrRegion: "FR", genre: "Traditional Pop", subgenre: "Chanson", mood: "Elegant", secondaryMood: "Romantic", energy: 35, tempo: 85, romanceScore: 99, nostalgiaScore: 100, confidenceScore: 60, cinematicScore: 92, peacefulScore: 85, danceScore: 25, darknessScore: 10, duration: "3:07", vibeTags: ["vintageParis", "roseColoredLife", "legendaryChanson", "blackAndWhiteFilm"], lyricalThemes: ["lifeInPink", "tenderWhispers", "eternalRomance"] },

  // ================= PORTUGUESE (15+ songs) =================
  { title: "Garota de Ipanema", artist: "Stan Getz, João Gilberto & Astrud Gilberto", language: "Portuguese", countryOrRegion: "BR", genre: "Bossa Nova", subgenre: "Jazz", mood: "Elegant", secondaryMood: "Peaceful", energy: 38, tempo: 128, romanceScore: 92, nostalgiaScore: 99, confidenceScore: 65, cinematicScore: 88, peacefulScore: 96, danceScore: 50, darknessScore: 10, duration: "5:22", vibeTags: ["ipanemaBeach", "goldenBossa", "vintageVinyl", "gentleSway"], lyricalThemes: ["girlFromIpanema", "passingBeauty", "poeticYearning"] },
  { title: "Águas de Março", artist: "Elis Regina & Antônio Carlos Jobim", language: "Portuguese", countryOrRegion: "BR", genre: "Bossa Nova", subgenre: "MPB", mood: "Peaceful", secondaryMood: "Happy", energy: 52, tempo: 142, romanceScore: 75, nostalgiaScore: 95, confidenceScore: 75, cinematicScore: 85, peacefulScore: 94, danceScore: 60, darknessScore: 12, duration: "3:32", vibeTags: ["watersOfMarch", "rainStream", "lifePhilosophy", "pureBossaMasterpiece"], lyricalThemes: ["streamOfLife", "rainClosingSummer", "hope"] },
  { title: "Ai Se Eu Te Pego", artist: "Michel Teló", language: "Portuguese", countryOrRegion: "BR", genre: "Sertanejo", subgenre: "Pop", mood: "Happy", secondaryMood: "Energetic", energy: 90, tempo: 96, romanceScore: 75, nostalgiaScore: 60, confidenceScore: 90, cinematicScore: 70, peacefulScore: 20, danceScore: 98, darknessScore: 5, duration: "2:46", vibeTags: ["brazilParty", "infectiousAccordion", "carnivalDance", "flirtatiousSmile"], lyricalThemes: ["ifICatchYou", "partyFlirt", "danceJoy"] },
];

async function enrich() {
  console.log(`Starting verification of ${SEED_TRACKS.length} seed tracks with official iTunes API...`);
  const enriched = [];

  for (let i = 0; i < SEED_TRACKS.length; i++) {
    const s = SEED_TRACKS[i];
    const query = `${s.artist} ${s.title}`;
    let trackInfo = null;

    try {
      const res = await fetch(`https://itunes.apple.com/search?term=${encodeURIComponent(query)}&entity=song&limit=1`);
      if (res.ok) {
        const data = await res.json();
        trackInfo = data.results?.[0];
      }
    } catch (err) {
      console.warn(`Failed search for ${query}`);
    }

    const previewUrl = trackInfo?.previewUrl || null;
    const artworkUrl = trackInfo?.artworkUrl100?.replace('100x100bb', '300x300bb') || trackInfo?.artworkUrl100 || null;
    const listenUrl = trackInfo?.trackViewUrl || `https://open.spotify.com/search/${encodeURIComponent(query)}`;

    enriched.push({
      id: `vm-${s.language.toLowerCase().slice(0, 3)}-${i + 1}`,
      title: s.title,
      artist: s.artist,
      language: s.language,
      countryOrRegion: s.countryOrRegion,
      genre: s.genre,
      subgenre: s.subgenre,
      mood: s.mood,
      secondaryMood: s.secondaryMood,
      energy: s.energy,
      tempo: s.tempo,
      vibeTags: s.vibeTags,
      lyricalThemes: s.lyricalThemes,
      romanceScore: s.romanceScore,
      nostalgiaScore: s.nostalgiaScore,
      confidenceScore: s.confidenceScore,
      cinematicScore: s.cinematicScore,
      peacefulScore: s.peacefulScore,
      danceScore: s.danceScore,
      darknessScore: s.darknessScore,
      popularity: 85,
      listenUrl,
      previewUrl,
      artworkUrl,
      source: previewUrl ? 'itunes-verified' : 'curated-editorial',
      duration: s.duration,
      bpm: s.tempo,
    });

    if ((i + 1) % 15 === 0 || i === SEED_TRACKS.length - 1) {
      console.log(`Processed ${i + 1}/${SEED_TRACKS.length} tracks... Verified previews: ${enriched.filter(x => x.previewUrl).length}`);
    }
  }

  const fileContent = `import { Song } from '../types';\n\nexport const VERIFIED_SONG_CATALOGUE: Song[] = ${JSON.stringify(enriched, null, 2)};\n`;
  fs.writeFileSync('src/data/songs.ts', fileContent);
  console.log(`Saved ${enriched.length} songs to src/data/songs.ts successfully!`);
}

enrich();
